#!/usr/local/bin/escript

main([]) ->
  io:format("Usage ./fizz_buzz [number]");
main([Input| _]) ->
  {ok, _} = fizz_buzz:start(),
  ParsedInput =
    case string:to_float(Input) of
      {error, no_float} ->
        case string:to_integer(Input) of
          {error, no_integer} -> Input;
          {Int, _Rest} -> Int
        end;
      {Float, _Rest} -> Float
    end,
  fizz_buzz:up_to(ParsedInput).
