#!/usr/local/bin/escript

main([]) ->
  io:format("Usage ./fizz_buzz [number]");
main([Input| _]) ->
  {ok, _} = fizz_buzz:start(),
  ParsedInput =
    case string:to_integer(Input) of
      {Int, _} -> Int;
      _ -> Input
    end,
  fizz_buzz:up_to(ParsedInput).
